language: c++

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - cmake-data
            - cmake
            - g++-4.9
            - swig
            - pkg-config 
            - libturbojpeg
            - libjpeg-turbo8-dev
            - mesa-common-dev
            - freeglut3-dev
            - libxrandr-dev
            - libxi-dev
            - libva-dev
            - libusb-1.0-0-dev
            - python3-dev
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"


before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make -j
