matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - cmake-data
            - cmake
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"


before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - $(CC) --version
