language: c++

matrix:
  include:
    - dist: bionic
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - cmake-data
            - cmake
            - swig
            - pkg-config 
            - libturbojpeg
            - libturbojpeg0-dev
            - libjpeg-turbo8-dev
            - mesa-common-dev
            - freeglut3-dev
            - libxrandr-dev
            - libxi-dev
            - libva-dev
            - libusb-1.0-0-dev
            - python3-dev
            - python-numpy


before_install:
  - eval "${MATRIX_EVAL}"


script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make -j
